### ISSUE TITLE
Excuse me, can you give the implementation of other federated methods in your experiments?

### ISSUE THREAD

**Issue by hwang24** [shangxinyi/CReFF-FL#1]
Excuse me, can you give the implementation of other federated methods in your experiments?
such as FedNova, CCVR, ...

**Comment by shangxinyi** [comment]
您好，我是尚心怡，我已收到您的邮件，会尽快给您回复，辛苦了！

**Comment by Believas** [comment]
same as above, email to you for experiments code. thank you

**Comment by shangxinyi** [comment]
您好，我是尚心怡，我已收到您的邮件，会尽快给您回复，辛苦了！
