### ISSUE TITLE
关于论文CReFF-FL中的CCVR实现

### ISSUE THREAD

**Issue by Bhongcheng** [shangxinyi/CReFF-FL#2]
请问方便提供论文中CCVR实现部分的代码嘛
万分感激

**Comment by shangxinyi** [comment]
您好，我是尚心怡，我已收到您的邮件，会尽快给您回复，辛苦了！

**Comment by harrylee999** [comment]
> 请问方便提供论文中CCVR实现部分的代码嘛 万分感激

请问你有CCVR的代码了吗？

**Comment by Bhongcheng** [comment]
> > 请问方便提供论文中CCVR实现部分的代码嘛 万分感激
> 
> 请问你有CCVR的代码了吗？

我找到一个学生的report有实现这个算法，但是应用到我的结果有问题，准确率一直在降低
https://github.com/dadodimauro/MLDL-Federated-Learning

**Comment by qizhuang-qz** [comment]
您好，关于您对比的CCVR的代码，方便提供一下吗，万分感激，我的邮箱是97qizhuang@gmail.com
